# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-01 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meaning_tamazight', models.CharField(max_length=200)),
                ('meaning_arabic', models.CharField(max_length=200)),
                ('added_at', models.DateTimeField(verbose_name='date added')),
            ],
        ),
    ]
