# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-06 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0002_auto_20180901_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='word_french',
            field=models.CharField(default='Not found. ', max_length=200),
            preserve_default=False,
        ),
    ]
